# Copyright (c) IBM Corporation 2021
# This file is defining Oracle Variables
oracledbaix19c:
  - /home/ansible/zips/oraclesw19c/AIX.PPC64_193000_db_home.zip
ora_user: oracle
ora_user_uid: 1521
ora_group: dba
ora_group_gid: 500
ora_oinstall_group: oinstall
ora_oinstall_group_gid: 501
ora_oper_group: oper
ora_oper_group_gid: 503
ora_home_profile: /home/{{ora_user}}
ora_install_group: oinstall
ora_version: "19.0.0.0.0"
ora_install_type: DB
ora_sid: orcl 
ora_pwd: Oracle4u
ora_character_set: WE8MSWIN1252
ora_fs: /oracle
ora_data_fs: /oradata 
ora_data_fs_size: 1G
ora_fs_size: 20G
ora_fs_vg: oravg
ora_inventory: "{{ora_fs}}/oraInventory"
ora_base: "{{ora_fs}}/base"
ora_home: "{{ora_fs}}/product/{{ora_version}}/database"
code_base_dir: "{{ora_home}}"
ora_db_fs_list:
  - { fs_name: "/datafiles", size: "8G" }
  - { fs_name: "/controlfiles", size: "2G" }
  - { fs_name: "/redologs", size: "4G" }
