---
galaxy_info:
  role_name: oracle_createdb 
  author: Bhargavaram Akula 
  description: Ansible role creates a test database using dbca silent option.
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
  - name: AIX
    versions:
    - all

  galaxy_tags: [aix]
  dependencies: []
